apiVersion: v1
kind: Pod
metadata:
  name: node-explorer-specific
spec:
  nodeName: "workenvironmenttwo"
  volumes:
    - name: host-root
      hostPath:
        path: /
  containers:
    - name: node-explorer
      image: alpine
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: host-root
          mountPath: /host
